version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - e2:6e:f1:77:1e:57:de:53:41:c1:60:27:50:d6:2d:29
            - d2:d1:bd:38:98:19:9a:ff:c6:33:72:20:72:1a:94:74
      - run:
          name: Setup VirtualEnv and Build
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=subasta_sa' >> $BASH_ENV
            npm install
            npm build
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to GCP via docker
          command: |
            ssh -o StrictHostKeyChecking=no haldamir.95@35.239.120.28 "/bin/bash ./deploy_app.sh $DOCKER_LOGIN/$IMAGE_NAME:$TAG"
